// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

// gRPC contract for the Carbonio preview backend interface.
//
// Error-mapping convention (HTTP status -> gRPC status code), single source of truth,
// consumed by the Go server error mapper and the Java SDK PreviewException mapping:
//   404 Not Found            -> NOT_FOUND
//   400 Bad Request          -> INVALID_ARGUMENT
//   422 Unprocessable Entity -> FAILED_PRECONDITION
//   500 Internal Server Error-> INTERNAL
//
// Streaming convention:
//   Downloads are server-streaming: the FIRST frame is always PreviewMetadata,
//   followed by zero or more chunk frames (~64KB each).
//   Uploads are client-streaming: the FIRST frame is always UploadMetadata,
//   followed by one or more data frames (~64KB each).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: preview.proto

package previewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query parameters shared by all download RPCs and (via UploadMetadata) uploads.
//
// Per-RPC applicability:
//
//	crop          — image PREVIEW only (GetImagePreview / PostImagePreview);
//	                thumbnails always use CENTER crop and ignore this field.
//	first_page,
//	last_page     — PDF and document PREVIEW only (GetPdfPreview,
//	                GetDocumentPreview, Post equivalents); thumbnail RPCs ignore.
//	lang_tag      — document endpoints only (GetDocumentPreview,
//	                GetDocumentThumbnail, Post equivalents); other RPCs ignore.
//	shape,
//	output_format,
//	quality,
//	area          — all thumbnail RPCs and image preview; PDF/doc preview ignore.
type PreviewParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- identity (path params for GET RPCs) ---
	FileId  string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // UUID; ignored for upload RPCs
	Version int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`            // ignored for upload RPCs
	Area    string `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"`                   // "WIDTHxHEIGHT" e.g. "320x240"; required for image + all thumbnails
	// --- format controls ---
	OutputFormat string `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // "jpeg" | "png" | "gif"; default "jpeg"
	Quality      string `protobuf:"bytes,5,opt,name=quality,proto3" json:"quality,omitempty"`                               // "lowest"|"low"|"medium"|"high"|"highest"; default "medium" (STRING bucket, not int)
	Shape        string `protobuf:"bytes,6,opt,name=shape,proto3" json:"shape,omitempty"`                                   // "rounded" | "rectangular"; default "rectangular"; thumbnail only; "rounded" forces png
	// --- routing ---
	ServiceType string `protobuf:"bytes,7,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"` // "files" | "chats"; required for GET RPCs
	OwnerId     string `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`             // UUID; was REST header "fileownerid"; CE ignores, Advanced uses for routing
	// --- image preview only ---
	Crop bool `protobuf:"varint,9,opt,name=crop,proto3" json:"crop,omitempty"` // true = cover/center-crop, false = scale-to-fit; image PREVIEW only (thumbnails hardcode their own)
	// --- pdf + document PREVIEW page range ---
	FirstPage int32 `protobuf:"varint,10,opt,name=first_page,json=firstPage,proto3" json:"first_page,omitempty"` // 1-based; 0 = server default (1)
	LastPage  int32 `protobuf:"varint,11,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`    // 0 = to end
	// --- document conversion locale ---
	LangTag       string `protobuf:"bytes,12,opt,name=lang_tag,json=langTag,proto3" json:"lang_tag,omitempty"` // IETF tag e.g. "en-US"; document endpoints only; default "en-US"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewParams) Reset() {
	*x = PreviewParams{}
	mi := &file_preview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewParams) ProtoMessage() {}

func (x *PreviewParams) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewParams.ProtoReflect.Descriptor instead.
func (*PreviewParams) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewParams) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *PreviewParams) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PreviewParams) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *PreviewParams) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *PreviewParams) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *PreviewParams) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *PreviewParams) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *PreviewParams) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PreviewParams) GetCrop() bool {
	if x != nil {
		return x.Crop
	}
	return false
}

func (x *PreviewParams) GetFirstPage() int32 {
	if x != nil {
		return x.FirstPage
	}
	return 0
}

func (x *PreviewParams) GetLastPage() int32 {
	if x != nil {
		return x.LastPage
	}
	return 0
}

func (x *PreviewParams) GetLangTag() string {
	if x != nil {
		return x.LangTag
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *PreviewParams         `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_preview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetParams() *PreviewParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type PreviewMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"` // total byte length; known because storage buffers full blob (<=32MB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewMetadata) Reset() {
	*x = PreviewMetadata{}
	mi := &file_preview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewMetadata) ProtoMessage() {}

func (x *PreviewMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewMetadata.ProtoReflect.Descriptor instead.
func (*PreviewMetadata) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{2}
}

func (x *PreviewMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *PreviewMetadata) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Download frame: metadata first, then >=0 chunk frames (~64KB each).
type PreviewChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PreviewChunk_Metadata
	//	*PreviewChunk_Chunk
	Payload       isPreviewChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewChunk) Reset() {
	*x = PreviewChunk{}
	mi := &file_preview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewChunk) ProtoMessage() {}

func (x *PreviewChunk) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewChunk.ProtoReflect.Descriptor instead.
func (*PreviewChunk) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewChunk) GetPayload() isPreviewChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PreviewChunk) GetMetadata() *PreviewMetadata {
	if x != nil {
		if x, ok := x.Payload.(*PreviewChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *PreviewChunk) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PreviewChunk_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPreviewChunk_Payload interface {
	isPreviewChunk_Payload()
}

type PreviewChunk_Metadata struct {
	Metadata *PreviewMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type PreviewChunk_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PreviewChunk_Metadata) isPreviewChunk_Payload() {}

func (*PreviewChunk_Chunk) isPreviewChunk_Payload() {}

type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *PreviewParams         `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_preview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{4}
}

func (x *UploadMetadata) GetParams() *PreviewParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// Upload frame: metadata first, then >=1 data frames (~64KB each).
type UploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadChunk_Metadata
	//	*UploadChunk_Data
	Payload       isUploadChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_preview_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{5}
}

func (x *UploadChunk) GetPayload() isUploadChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadChunk) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadChunk_Payload interface {
	isUploadChunk_Payload()
}

type UploadChunk_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadChunk_Metadata) isUploadChunk_Payload() {}

func (*UploadChunk_Data) isUploadChunk_Payload() {}

var File_preview_proto protoreflect.FileDescriptor

const file_preview_proto_rawDesc = "" +
	"\n" +
	"\rpreview.proto\x12\apreview\"\xd4\x02\n" +
	"\rPreviewParams\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x12\n" +
	"\x04area\x18\x03 \x01(\tR\x04area\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\x12\x18\n" +
	"\aquality\x18\x05 \x01(\tR\aquality\x12\x14\n" +
	"\x05shape\x18\x06 \x01(\tR\x05shape\x12!\n" +
	"\fservice_type\x18\a \x01(\tR\vserviceType\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12\x12\n" +
	"\x04crop\x18\t \x01(\bR\x04crop\x12\x1d\n" +
	"\n" +
	"first_page\x18\n" +
	" \x01(\x05R\tfirstPage\x12\x1b\n" +
	"\tlast_page\x18\v \x01(\x05R\blastPage\x12\x19\n" +
	"\blang_tag\x18\f \x01(\tR\alangTag\"<\n" +
	"\n" +
	"GetRequest\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.preview.PreviewParamsR\x06params\"F\n" +
	"\x0fPreviewMetadata\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"i\n" +
	"\fPreviewChunk\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.preview.PreviewMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"@\n" +
	"\x0eUploadMetadata\x12.\n" +
	"\x06params\x18\x01 \x01(\v2\x16.preview.PreviewParamsR\x06params\"e\n" +
	"\vUploadChunk\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.preview.UploadMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload2\xc4\x06\n" +
	"\x0ePreviewService\x12?\n" +
	"\x0fGetImagePreview\x12\x13.preview.GetRequest\x1a\x15.preview.PreviewChunk0\x01\x12A\n" +
	"\x11GetImageThumbnail\x12\x13.preview.GetRequest\x1a\x15.preview.PreviewChunk0\x01\x12=\n" +
	"\rGetPdfPreview\x12\x13.preview.GetRequest\x1a\x15.preview.PreviewChunk0\x01\x12?\n" +
	"\x0fGetPdfThumbnail\x12\x13.preview.GetRequest\x1a\x15.preview.PreviewChunk0\x01\x12B\n" +
	"\x12GetDocumentPreview\x12\x13.preview.GetRequest\x1a\x15.preview.PreviewChunk0\x01\x12D\n" +
	"\x14GetDocumentThumbnail\x12\x13.preview.GetRequest\x1a\x15.preview.PreviewChunk0\x01\x12C\n" +
	"\x10PostImagePreview\x12\x14.preview.UploadChunk\x1a\x15.preview.PreviewChunk(\x010\x01\x12E\n" +
	"\x12PostImageThumbnail\x12\x14.preview.UploadChunk\x1a\x15.preview.PreviewChunk(\x010\x01\x12A\n" +
	"\x0ePostPdfPreview\x12\x14.preview.UploadChunk\x1a\x15.preview.PreviewChunk(\x010\x01\x12C\n" +
	"\x10PostPdfThumbnail\x12\x14.preview.UploadChunk\x1a\x15.preview.PreviewChunk(\x010\x01\x12F\n" +
	"\x13PostDocumentPreview\x12\x14.preview.UploadChunk\x1a\x15.preview.PreviewChunk(\x010\x01\x12H\n" +
	"\x15PostDocumentThumbnail\x12\x14.preview.UploadChunk\x1a\x15.preview.PreviewChunk(\x010\x01Bj\n" +
	"%com.zextras.carbonio.preview.sdk.grpcP\x01Z?github.com/zextras/carbonio-preview-ce/server/grpc/pb;previewpbb\x06proto3"

var (
	file_preview_proto_rawDescOnce sync.Once
	file_preview_proto_rawDescData []byte
)

func file_preview_proto_rawDescGZIP() []byte {
	file_preview_proto_rawDescOnce.Do(func() {
		file_preview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preview_proto_rawDesc), len(file_preview_proto_rawDesc)))
	})
	return file_preview_proto_rawDescData
}

var file_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_preview_proto_goTypes = []any{
	(*PreviewParams)(nil),   // 0: preview.PreviewParams
	(*GetRequest)(nil),      // 1: preview.GetRequest
	(*PreviewMetadata)(nil), // 2: preview.PreviewMetadata
	(*PreviewChunk)(nil),    // 3: preview.PreviewChunk
	(*UploadMetadata)(nil),  // 4: preview.UploadMetadata
	(*UploadChunk)(nil),     // 5: preview.UploadChunk
}
var file_preview_proto_depIdxs = []int32{
	0,  // 0: preview.GetRequest.params:type_name -> preview.PreviewParams
	2,  // 1: preview.PreviewChunk.metadata:type_name -> preview.PreviewMetadata
	0,  // 2: preview.UploadMetadata.params:type_name -> preview.PreviewParams
	4,  // 3: preview.UploadChunk.metadata:type_name -> preview.UploadMetadata
	1,  // 4: preview.PreviewService.GetImagePreview:input_type -> preview.GetRequest
	1,  // 5: preview.PreviewService.GetImageThumbnail:input_type -> preview.GetRequest
	1,  // 6: preview.PreviewService.GetPdfPreview:input_type -> preview.GetRequest
	1,  // 7: preview.PreviewService.GetPdfThumbnail:input_type -> preview.GetRequest
	1,  // 8: preview.PreviewService.GetDocumentPreview:input_type -> preview.GetRequest
	1,  // 9: preview.PreviewService.GetDocumentThumbnail:input_type -> preview.GetRequest
	5,  // 10: preview.PreviewService.PostImagePreview:input_type -> preview.UploadChunk
	5,  // 11: preview.PreviewService.PostImageThumbnail:input_type -> preview.UploadChunk
	5,  // 12: preview.PreviewService.PostPdfPreview:input_type -> preview.UploadChunk
	5,  // 13: preview.PreviewService.PostPdfThumbnail:input_type -> preview.UploadChunk
	5,  // 14: preview.PreviewService.PostDocumentPreview:input_type -> preview.UploadChunk
	5,  // 15: preview.PreviewService.PostDocumentThumbnail:input_type -> preview.UploadChunk
	3,  // 16: preview.PreviewService.GetImagePreview:output_type -> preview.PreviewChunk
	3,  // 17: preview.PreviewService.GetImageThumbnail:output_type -> preview.PreviewChunk
	3,  // 18: preview.PreviewService.GetPdfPreview:output_type -> preview.PreviewChunk
	3,  // 19: preview.PreviewService.GetPdfThumbnail:output_type -> preview.PreviewChunk
	3,  // 20: preview.PreviewService.GetDocumentPreview:output_type -> preview.PreviewChunk
	3,  // 21: preview.PreviewService.GetDocumentThumbnail:output_type -> preview.PreviewChunk
	3,  // 22: preview.PreviewService.PostImagePreview:output_type -> preview.PreviewChunk
	3,  // 23: preview.PreviewService.PostImageThumbnail:output_type -> preview.PreviewChunk
	3,  // 24: preview.PreviewService.PostPdfPreview:output_type -> preview.PreviewChunk
	3,  // 25: preview.PreviewService.PostPdfThumbnail:output_type -> preview.PreviewChunk
	3,  // 26: preview.PreviewService.PostDocumentPreview:output_type -> preview.PreviewChunk
	3,  // 27: preview.PreviewService.PostDocumentThumbnail:output_type -> preview.PreviewChunk
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_preview_proto_init() }
func file_preview_proto_init() {
	if File_preview_proto != nil {
		return
	}
	file_preview_proto_msgTypes[3].OneofWrappers = []any{
		(*PreviewChunk_Metadata)(nil),
		(*PreviewChunk_Chunk)(nil),
	}
	file_preview_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadChunk_Metadata)(nil),
		(*UploadChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preview_proto_rawDesc), len(file_preview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_preview_proto_goTypes,
		DependencyIndexes: file_preview_proto_depIdxs,
		MessageInfos:      file_preview_proto_msgTypes,
	}.Build()
	File_preview_proto = out.File
	file_preview_proto_goTypes = nil
	file_preview_proto_depIdxs = nil
}
