// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

// gRPC contract for the Carbonio preview backend interface.
//
// Error-mapping convention (HTTP status -> gRPC status code), single source of truth,
// consumed by the Go server error mapper and the Java SDK PreviewException mapping:
//   404 Not Found            -> NOT_FOUND
//   400 Bad Request          -> INVALID_ARGUMENT
//   422 Unprocessable Entity -> FAILED_PRECONDITION
//   500 Internal Server Error-> INTERNAL
//
// Streaming convention:
//   Downloads are server-streaming: the FIRST frame is always PreviewMetadata,
//   followed by zero or more chunk frames (~64KB each).
//   Uploads are client-streaming: the FIRST frame is always UploadMetadata,
//   followed by one or more data frames (~64KB each).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: preview.proto

package previewpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreviewService_GetImagePreview_FullMethodName       = "/preview.PreviewService/GetImagePreview"
	PreviewService_GetImageThumbnail_FullMethodName     = "/preview.PreviewService/GetImageThumbnail"
	PreviewService_GetPdfPreview_FullMethodName         = "/preview.PreviewService/GetPdfPreview"
	PreviewService_GetPdfThumbnail_FullMethodName       = "/preview.PreviewService/GetPdfThumbnail"
	PreviewService_GetDocumentPreview_FullMethodName    = "/preview.PreviewService/GetDocumentPreview"
	PreviewService_GetDocumentThumbnail_FullMethodName  = "/preview.PreviewService/GetDocumentThumbnail"
	PreviewService_GetVideoPreview_FullMethodName       = "/preview.PreviewService/GetVideoPreview"
	PreviewService_GetVideoThumbnail_FullMethodName     = "/preview.PreviewService/GetVideoThumbnail"
	PreviewService_PostImagePreview_FullMethodName      = "/preview.PreviewService/PostImagePreview"
	PreviewService_PostImageThumbnail_FullMethodName    = "/preview.PreviewService/PostImageThumbnail"
	PreviewService_PostPdfPreview_FullMethodName        = "/preview.PreviewService/PostPdfPreview"
	PreviewService_PostPdfThumbnail_FullMethodName      = "/preview.PreviewService/PostPdfThumbnail"
	PreviewService_PostDocumentPreview_FullMethodName   = "/preview.PreviewService/PostDocumentPreview"
	PreviewService_PostDocumentThumbnail_FullMethodName = "/preview.PreviewService/PostDocumentThumbnail"
)

// PreviewServiceClient is the client API for PreviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreviewServiceClient interface {
	// ---- Downloads: server-streaming, metadata ALWAYS first ----
	GetImagePreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	GetImageThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	GetPdfPreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	GetPdfThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	GetDocumentPreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	GetDocumentThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	GetVideoPreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	GetVideoThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error)
	// ---- Uploads: client-streaming in, server-streaming out (mailbox only) ----
	PostImagePreview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error)
	PostImageThumbnail(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error)
	PostPdfPreview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error)
	PostPdfThumbnail(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error)
	PostDocumentPreview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error)
	PostDocumentThumbnail(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error)
}

type previewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreviewServiceClient(cc grpc.ClientConnInterface) PreviewServiceClient {
	return &previewServiceClient{cc}
}

func (c *previewServiceClient) GetImagePreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[0], PreviewService_GetImagePreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetImagePreviewClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) GetImageThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[1], PreviewService_GetImageThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetImageThumbnailClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) GetPdfPreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[2], PreviewService_GetPdfPreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetPdfPreviewClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) GetPdfThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[3], PreviewService_GetPdfThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetPdfThumbnailClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) GetDocumentPreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[4], PreviewService_GetDocumentPreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetDocumentPreviewClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) GetDocumentThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[5], PreviewService_GetDocumentThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetDocumentThumbnailClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) GetVideoPreview(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[6], PreviewService_GetVideoPreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetVideoPreviewClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) GetVideoThumbnail(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[7], PreviewService_GetVideoThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, PreviewChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetVideoThumbnailClient = grpc.ServerStreamingClient[PreviewChunk]

func (c *previewServiceClient) PostImagePreview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[8], PreviewService_PostImagePreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, PreviewChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostImagePreviewClient = grpc.BidiStreamingClient[UploadChunk, PreviewChunk]

func (c *previewServiceClient) PostImageThumbnail(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[9], PreviewService_PostImageThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, PreviewChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostImageThumbnailClient = grpc.BidiStreamingClient[UploadChunk, PreviewChunk]

func (c *previewServiceClient) PostPdfPreview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[10], PreviewService_PostPdfPreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, PreviewChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostPdfPreviewClient = grpc.BidiStreamingClient[UploadChunk, PreviewChunk]

func (c *previewServiceClient) PostPdfThumbnail(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[11], PreviewService_PostPdfThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, PreviewChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostPdfThumbnailClient = grpc.BidiStreamingClient[UploadChunk, PreviewChunk]

func (c *previewServiceClient) PostDocumentPreview(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[12], PreviewService_PostDocumentPreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, PreviewChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostDocumentPreviewClient = grpc.BidiStreamingClient[UploadChunk, PreviewChunk]

func (c *previewServiceClient) PostDocumentThumbnail(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, PreviewChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PreviewService_ServiceDesc.Streams[13], PreviewService_PostDocumentThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, PreviewChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostDocumentThumbnailClient = grpc.BidiStreamingClient[UploadChunk, PreviewChunk]

// PreviewServiceServer is the server API for PreviewService service.
// All implementations must embed UnimplementedPreviewServiceServer
// for forward compatibility.
type PreviewServiceServer interface {
	// ---- Downloads: server-streaming, metadata ALWAYS first ----
	GetImagePreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	GetImageThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	GetPdfPreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	GetPdfThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	GetDocumentPreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	GetDocumentThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	GetVideoPreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	GetVideoThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error
	// ---- Uploads: client-streaming in, server-streaming out (mailbox only) ----
	PostImagePreview(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error
	PostImageThumbnail(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error
	PostPdfPreview(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error
	PostPdfThumbnail(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error
	PostDocumentPreview(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error
	PostDocumentThumbnail(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error
	mustEmbedUnimplementedPreviewServiceServer()
}

// UnimplementedPreviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreviewServiceServer struct{}

func (UnimplementedPreviewServiceServer) GetImagePreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetImagePreview not implemented")
}
func (UnimplementedPreviewServiceServer) GetImageThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetImageThumbnail not implemented")
}
func (UnimplementedPreviewServiceServer) GetPdfPreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetPdfPreview not implemented")
}
func (UnimplementedPreviewServiceServer) GetPdfThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetPdfThumbnail not implemented")
}
func (UnimplementedPreviewServiceServer) GetDocumentPreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetDocumentPreview not implemented")
}
func (UnimplementedPreviewServiceServer) GetDocumentThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetDocumentThumbnail not implemented")
}
func (UnimplementedPreviewServiceServer) GetVideoPreview(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetVideoPreview not implemented")
}
func (UnimplementedPreviewServiceServer) GetVideoThumbnail(*GetRequest, grpc.ServerStreamingServer[PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method GetVideoThumbnail not implemented")
}
func (UnimplementedPreviewServiceServer) PostImagePreview(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method PostImagePreview not implemented")
}
func (UnimplementedPreviewServiceServer) PostImageThumbnail(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method PostImageThumbnail not implemented")
}
func (UnimplementedPreviewServiceServer) PostPdfPreview(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method PostPdfPreview not implemented")
}
func (UnimplementedPreviewServiceServer) PostPdfThumbnail(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method PostPdfThumbnail not implemented")
}
func (UnimplementedPreviewServiceServer) PostDocumentPreview(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method PostDocumentPreview not implemented")
}
func (UnimplementedPreviewServiceServer) PostDocumentThumbnail(grpc.BidiStreamingServer[UploadChunk, PreviewChunk]) error {
	return status.Error(codes.Unimplemented, "method PostDocumentThumbnail not implemented")
}
func (UnimplementedPreviewServiceServer) mustEmbedUnimplementedPreviewServiceServer() {}
func (UnimplementedPreviewServiceServer) testEmbeddedByValue()                        {}

// UnsafePreviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreviewServiceServer will
// result in compilation errors.
type UnsafePreviewServiceServer interface {
	mustEmbedUnimplementedPreviewServiceServer()
}

func RegisterPreviewServiceServer(s grpc.ServiceRegistrar, srv PreviewServiceServer) {
	// If the following call panics, it indicates UnimplementedPreviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreviewService_ServiceDesc, srv)
}

func _PreviewService_GetImagePreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetImagePreview(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetImagePreviewServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_GetImageThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetImageThumbnail(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetImageThumbnailServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_GetPdfPreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetPdfPreview(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetPdfPreviewServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_GetPdfThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetPdfThumbnail(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetPdfThumbnailServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_GetDocumentPreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetDocumentPreview(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetDocumentPreviewServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_GetDocumentThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetDocumentThumbnail(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetDocumentThumbnailServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_GetVideoPreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetVideoPreview(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetVideoPreviewServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_GetVideoThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PreviewServiceServer).GetVideoThumbnail(m, &grpc.GenericServerStream[GetRequest, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_GetVideoThumbnailServer = grpc.ServerStreamingServer[PreviewChunk]

func _PreviewService_PostImagePreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PreviewServiceServer).PostImagePreview(&grpc.GenericServerStream[UploadChunk, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostImagePreviewServer = grpc.BidiStreamingServer[UploadChunk, PreviewChunk]

func _PreviewService_PostImageThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PreviewServiceServer).PostImageThumbnail(&grpc.GenericServerStream[UploadChunk, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostImageThumbnailServer = grpc.BidiStreamingServer[UploadChunk, PreviewChunk]

func _PreviewService_PostPdfPreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PreviewServiceServer).PostPdfPreview(&grpc.GenericServerStream[UploadChunk, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostPdfPreviewServer = grpc.BidiStreamingServer[UploadChunk, PreviewChunk]

func _PreviewService_PostPdfThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PreviewServiceServer).PostPdfThumbnail(&grpc.GenericServerStream[UploadChunk, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostPdfThumbnailServer = grpc.BidiStreamingServer[UploadChunk, PreviewChunk]

func _PreviewService_PostDocumentPreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PreviewServiceServer).PostDocumentPreview(&grpc.GenericServerStream[UploadChunk, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostDocumentPreviewServer = grpc.BidiStreamingServer[UploadChunk, PreviewChunk]

func _PreviewService_PostDocumentThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PreviewServiceServer).PostDocumentThumbnail(&grpc.GenericServerStream[UploadChunk, PreviewChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PreviewService_PostDocumentThumbnailServer = grpc.BidiStreamingServer[UploadChunk, PreviewChunk]

// PreviewService_ServiceDesc is the grpc.ServiceDesc for PreviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "preview.PreviewService",
	HandlerType: (*PreviewServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetImagePreview",
			Handler:       _PreviewService_GetImagePreview_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetImageThumbnail",
			Handler:       _PreviewService_GetImageThumbnail_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPdfPreview",
			Handler:       _PreviewService_GetPdfPreview_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPdfThumbnail",
			Handler:       _PreviewService_GetPdfThumbnail_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDocumentPreview",
			Handler:       _PreviewService_GetDocumentPreview_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDocumentThumbnail",
			Handler:       _PreviewService_GetDocumentThumbnail_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetVideoPreview",
			Handler:       _PreviewService_GetVideoPreview_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetVideoThumbnail",
			Handler:       _PreviewService_GetVideoThumbnail_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PostImagePreview",
			Handler:       _PreviewService_PostImagePreview_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PostImageThumbnail",
			Handler:       _PreviewService_PostImageThumbnail_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PostPdfPreview",
			Handler:       _PreviewService_PostPdfPreview_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PostPdfThumbnail",
			Handler:       _PreviewService_PostPdfThumbnail_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PostDocumentPreview",
			Handler:       _PreviewService_PostDocumentPreview_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PostDocumentThumbnail",
			Handler:       _PreviewService_PostDocumentThumbnail_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "preview.proto",
}
