# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com
#
# SPDX-License-Identifier: AGPL-3.0-only

repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
        language_version: python3.8

-   repo: https://github.com/python/black.git
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.3
    hooks:
    -   id: bandit
        language_version: python3.8

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^tests/
      language_version: python3.8

-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.14.0
    hooks:
        - id: reuse
          exclude: Dockerfile

-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python -m unittest discover
        language: python
        additional_dependencies: [
            python-multipart, FastAPI, uvicorn, gunicorn, Pillow, pdfrw, responses, psutil
        ]
        'types': [python]
        pass_filenames: false
        stages: [commit]