// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

package config

import "testing"

// TestConfigsTxt_NonEmpty verifies the embedded configuration documentation is
// non-empty (the configs.txt content is generated by cmd/configdocs and embedded
// at compile time).
func TestConfigsTxt_NonEmpty(t *testing.T) {
	if ConfigsTxt() == "" {
		t.Error("ConfigsTxt() must return the embedded configs.txt content, got empty string")
	}
}
