// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

package config

import _ "embed"

//go:embed configs.md
var configsMdData string

// ConfigsMd returns the embedded Markdown configuration documentation.
// The content is generated by cmd/configdocs and embedded at compile time.
// It is used by the --setup flag handler to print config documentation
// to the operator.
func ConfigsMd() string {
	return configsMdData
}
