// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

package config

import _ "embed"

//go:embed configs.txt
var configsTxtData string

// ConfigsTxt returns the embedded plain-text configuration documentation.
// The content is generated by cmd/configdocs and embedded at compile time.
// A later task will use this in the --setup flag handler.
func ConfigsTxt() string {
	return configsTxtData
}
