// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

// Package docs exposes the committed, generated documentation embedded into
// the binary (e.g. for the --setup config reference).
package docs

import _ "embed"

//go:embed configs.md
var configsMdData string

// ConfigsMd returns the embedded Markdown configuration reference
// (generated by cmd/configdocs, the same content as docs/configs.md).
func ConfigsMd() string { return configsMdData }
