// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

package docs

import "testing"

// TestConfigsMd_NonEmpty verifies the embedded configuration documentation is
// non-empty (the docs/configs.md content is generated by cmd/configdocs and
// embedded at compile time via go:embed).
func TestConfigsMd_NonEmpty(t *testing.T) {
	if ConfigsMd() == "" {
		t.Error("ConfigsMd() must return the embedded configs.md content, got empty string")
	}
}
