// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

package apispec

import (
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humago"
)

// NewAPI constructs the huma API for this service over the given mux. It is the
// SINGLE place the huma.Config is built: both the live server (via
// server.newHumaAPI) and cmd/gendocs call it, so the spec committed under docs/
// is generated from the very config the binary routes traffic through.
//
// The config is built from scratch rather than from huma.DefaultConfig because
// DefaultConfig installs the SchemaLinkTransformer via CreateHooks — it injects
// $schema fields into every response body, which conflicts with our
// FastAPI-compatible error model (no $schema, no Link headers). For the same
// reason SchemasPath stays empty: with no transformer there is nothing to point
// a /schemas route at.
//
// No doc routes are ever registered: OpenAPIPath, DocsPath and SchemasPath are
// all "", which is how huma is told to register no built-in route for that
// group. The OpenAPI document is a BUILD-TIME artefact (docs/openapi.yaml,
// docs/openapi.json) generated by cmd/gendocs from these same registrations, so
// serving it at runtime could only ever return what is already committed in the
// repository. A production node has no reason to publish its API surface.
func NewAPI(mux *http.ServeMux) huma.API {
	registry := huma.NewMapRegistry("#/components/schemas/", huma.DefaultSchemaNamer)
	cfg := huma.Config{
		OpenAPI: &huma.OpenAPI{
			OpenAPI: "3.1.0",
			Info: &huma.Info{
				Title:       "preview",
				Version:     "latest",
				Description: "Preview service.",
			},
			Components: &huma.Components{
				Schemas: registry,
			},
		},
		// Empty = huma registers no built-in route for that group.
		OpenAPIPath:   "",
		DocsPath:      "",
		SchemasPath:   "",
		Formats:       huma.DefaultFormats,
		DefaultFormat: "application/json",
		// No CreateHooks → no SchemaLinkTransformer → no $schema injection.
	}
	return humago.New(mux, cfg)
}
