// SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

package apispec_test

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/zextras/carbonio-preview-ce/v3/server/apispec"
)

// These tests replace the ones that used to cover the hand-rolled
// server/docs.go handlers (which served an embedded, duplicated copy of the
// generated spec). Nothing serves the spec at runtime any more: it is a
// build-time artefact under docs/, generated by cmd/gendocs from the very
// registrations exercised here, so what these tests pin is that the doc
// endpoints are gone and the real operations are not.
//
// They deliberately live in the cgo-free apispec package: package server is
// cgo-tainted through render (libvips/pdfium), while apispec is not, so this
// coverage runs anywhere.

// buildMux returns a mux with all operations registered via stubs, built
// through the same constructor the live server and cmd/gendocs use.
func buildMux() *http.ServeMux {
	mux := http.NewServeMux()
	api := apispec.NewAPI(mux)
	apispec.RegisterStubs(api)
	return mux
}

func do(mux *http.ServeMux, method, path string) *httptest.ResponseRecorder {
	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, httptest.NewRequest(method, path, nil))
	return rec
}

// docRoutes are the endpoints huma would serve if OpenAPIPath/DocsPath were
// ever set: the four spec documents it derives from the single OpenAPIPath
// base, plus the Swagger UI page.
var docRoutes = []string{
	"/openapi.json",
	"/openapi.yaml",
	"/openapi-3.0.json",
	"/openapi-3.0.yaml",
	"/docs",
}

// TestDocRoutes_AreNotRegistered verifies no spec or docs endpoint exists. The
// OpenAPI document is redundant with the committed docs/openapi.yaml by
// construction — both come from these same registrations — so a production node
// has nothing to gain by publishing it.
func TestDocRoutes_AreNotRegistered(t *testing.T) {
	mux := buildMux()

	for _, path := range docRoutes {
		t.Run(path, func(t *testing.T) {
			if rec := do(mux, http.MethodGet, path); rec.Code != http.StatusNotFound {
				t.Errorf("GET %s: status = %d, want 404", path, rec.Code)
			}
			// Not merely method-gated: the pattern must not exist at all, so a
			// non-GET is a 404 too (a registered GET-only route would give 405).
			if rec := do(mux, http.MethodPost, path); rec.Code != http.StatusNotFound {
				t.Errorf("POST %s: status = %d, want 404", path, rec.Code)
			}
		})
	}
}

// TestOperations_StayRouted verifies that dropping the doc routes gates ONLY
// the doc routes: the real API operations are registered as before.
func TestOperations_StayRouted(t *testing.T) {
	if rec := do(buildMux(), http.MethodGet, "/health/live/"); rec.Code != http.StatusOK {
		t.Errorf("GET /health/live/: status = %d, want 200", rec.Code)
	}
}

// TestSchemasPath_NeverRegistered verifies huma's /schemas route is off too:
// this API installs no SchemaLinkTransformer, so there is nothing for it to
// point at.
func TestSchemasPath_NeverRegistered(t *testing.T) {
	if rec := do(buildMux(), http.MethodGet, "/schemas/ErrorModel.json"); rec.Code != http.StatusNotFound {
		t.Errorf("GET /schemas/...: status = %d, want 404", rec.Code)
	}
}
